### ISSUE TITLE
Error When checkIgnore Ignores An Error

### ISSUE THREAD

**Issue by armordog** [tandibar/ng-rollbar#45]
When I use the `checkIgnore` configuration option, I get a `Rollbar: TypeError: Cannot read property 'result' of undefined` error everytime checkIgnore returns true.

The error originates here: https://github.com/tandibar/ng-rollbar/blob/master/ng-rollbar.js#L13

It appears the Rollbar.log() callback function still gets called but with no arguments.

The callback should probably do nothing if `err` is `undefined.

**Comment by jpike88** [comment]
A PR request is welcome. Your use case is niche enough that I'd expect you to do the dirty work on this one, I'm going to guess a very small majority of devs actually use checkIgnore

**Comment by armordog** [comment]
The case of checkIgnore not _always_ returning `false` is "niche"?
What is the purpose of checkIgnore then?

**Comment by jpike88** [comment]
This library is simply a wrapper and is maintained casually by a bunch of like minded people. None of us are affiliated with Rollbar.JS and tweak this as needed to meet our needs.

To answer your second question, I wouldn't know because this is the first time I knew about checkIgnore. I don't see anywhere in this codebase where it's really taken into account, and I don't know whether the problem lies with this library or Rollbar JS itself... perhaps an update of the embedded RollbarJS library might not hurt. If you see any specific improvements you're free to submit a PR.
